services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: unless-stopped
    ports:
      - '6379:6379' # Redis port
      - '8001:8001' # RedisInsight web UI
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD} # Optional, recommended for production
    volumes:
      - redis_data:/data

volumes:
  redis_data:
